name: Build Skyscraper ARM64

on:
  workflow_dispatch:
    inputs:
      sk_tag:
        description: 'Skyscraper version tag'
        required: true
        default: '3.17.5'
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  build-arm64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build on aarch64 (Ubuntu 22.04)
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu22.04
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          install: |
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
              build-essential git clang pkg-config \
              ca-certificates \
              qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools \
              libssl-dev zlib1g-dev libcurl4-openssl-dev \
              libprotobuf-dev protobuf-compiler \
              libarchive-dev libzip-dev \
              libpng-dev libjpeg-dev libfreetype6-dev
            update-ca-certificates
          run: |
            set -euo pipefail

            # Ensure we don't force an unsupported SSL backend
            git config --global --unset http.sslBackend || true

            echo "Using Skyscraper tag: ${{ inputs.sk_tag || '3.17.5' }}"
            SK_TAG="${{ inputs.sk_tag || '3.17.5' }}"

            # Fetch Skyscraper source
            git clone --depth 1 --branch "${SK_TAG}" https://github.com/Gemba/skyscraper.git
            cd skyscraper

            # Use clang explicitly
            export QMAKE_CC=clang
            export QMAKE_CXX=clang++

            qmake -v
            qmake
            make -j"$(nproc)"

            file Skyscraper || true
            strip Skyscraper || true

            # Package artifact
            tar czf ../Skyscraper.aarch64.${SK_TAG}.tar.gz Skyscraper
            cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Skyscraper.aarch64
          path: Skyscraper.aarch64.*.tar.gz
